// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALZV72E9xKA5eKTN4T__yGagLpiXbTwJM',
    appId: '1:321843251004:web:dc0a3c53885ced43310039',
    messagingSenderId: '321843251004',
    projectId: 'washcar2-1f6b7',
    authDomain: 'washcar2-1f6b7.firebaseapp.com',
    storageBucket: 'washcar2-1f6b7.appspot.com',
    measurementId: 'G-4950629TRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ8wilsX2IMecIlU7rjdheJgywh7TUkfM',
    appId: '1:321843251004:android:ff2c9531930642d0310039',
    messagingSenderId: '321843251004',
    projectId: 'washcar2-1f6b7',
    storageBucket: 'washcar2-1f6b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT2K2MpLwUIO6XbbyP5Vmqgqf5q5A1siA',
    appId: '1:321843251004:ios:56e6147315d564c9310039',
    messagingSenderId: '321843251004',
    projectId: 'washcar2-1f6b7',
    storageBucket: 'washcar2-1f6b7.appspot.com',
    iosClientId: '321843251004-nepnaj3c4b0q288vi1lu1p6lrjcgfkev.apps.googleusercontent.com',
    iosBundleId: 'com.example.testWashCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT2K2MpLwUIO6XbbyP5Vmqgqf5q5A1siA',
    appId: '1:321843251004:ios:56e6147315d564c9310039',
    messagingSenderId: '321843251004',
    projectId: 'washcar2-1f6b7',
    storageBucket: 'washcar2-1f6b7.appspot.com',
    iosClientId: '321843251004-nepnaj3c4b0q288vi1lu1p6lrjcgfkev.apps.googleusercontent.com',
    iosBundleId: 'com.example.testWashCar',
  );
}
